CREATE TABLE fichas_alumnos_tmp (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
numIdFichaAlumno INT(10),
strResumenInformee VARCHAR(50),
fecFecha DATE,	
memComentarios VARCHAR(500),	
numNota	Decimal(10,2),
numIdCursoAcademico	INT(10),
numIdConvocatoria INT(5),
blnDefinitivo INT(2),	
numIdAlumno INT(10),	
numIdCalificacion INT(10),		
numIdClase INT(10),		
numIdGrupo INT(10),		
blnVisibleConnect INT(2),		
blnNoMostrarNumericoConnect INT(2),			
numIdAsignatura INT(5),			
blnBoletinPublicadoConnect INT(2),			
numIdCliente INT(5),			
numEstadoComunicacion INT(2),			
numIdPersonal INT(5),			
fecCambioEstadoComunicacion	DATE,
strEstadoComunicacion VARCHAR(50),
blnFirmada iNT(2),	
fecFirma DATE,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)